const actions = {
    
    BUTTONTASKACTIVE: "BUTTONTASKACTIVE",
    BUTTONNEWPROJECT: "BUTTONNEWPROJECT",
    BUTTONMODIFYPROJECT: "BUTTONMODIFYPROJECT",
    DISPLAYTASK: "DISPLAYTASK",
    ACTIVEFORMADDMEMBERS: "ACTIVEFORMADDMEMBERS",
    LISTADDTOCARD: 'LISTADDTOCARD',
    SPINNER: 'SPINNER'

}
export default actions