const actions = {
    
    BUTTONTASKACTIVE: "BUTTONTASKACTIVE",
    BUTTONNEWPROJECT: "BUTTONNEWPROJECT",
    BUTTONMODIFYPROJECT: "BUTTONMODIFYPROJECT",
    DISPLAYTASK: "DISPLAYTASK"

}
export default actions